### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by llvmpic** [zeha/xc32#3]
Please please could you add a README.md that gives a quick clue on how to make use of this?  I think a lot of great work was probably done here, but as with many microchip tool suites, it's hard to figure out how to get it going.

**Comment by zeha** [comment]
Depends on what you want to do. If you come up with a PR adding documentation I'll gladly merge it.

**Comment by llvmpic** [comment]
ok.. If you can teach me how to build xc32 from this repository, I'll happily put what you tell me together into a PR!

**Comment by zeha** [comment]
I do not know how to build XC32 from the sources. Microchip has docs somewhere, but it’s unclear if building works from this repository.

**Comment by llvmpic** [comment]
Oh darn.  I was really hoping you knew how to get it built :)

The quest to rebuild the microchip tools goes on :)

Jonathan
